using API.Data;
using API.DTOs;
using API.Entities;
using API.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Cryptography;
using System.Text;

namespace API.Controllers
{
    public class AccountController : BaseApiController
    {
        private readonly DataContext _context;
        private readonly ITokenService _tokenService;

        public AccountController (DataContext context, ITokenService tokenService)
        {
            _context = context;
            _tokenService = tokenService;
        }

        [HttpPost("register")]
        public async Task<ActionResult<UserDto>> Register(RegisterDto registerDto)
        {
            if(await UserExists(registerDto.userName)) return BadRequest("UserName is Taken");

           
            using var hmac = new HMACSHA512();

            var user = new AppUser 
            { 
                UserName = registerDto.userName.ToLower(), 
                PasswordHash = hmac.ComputeHash(Encoding.UTF8.GetBytes(registerDto.password)),
                PasswordSalt = hmac.Key,
            };
            _context.Users.Add(user);
            await _context.SaveChangesAsync();

            

            return  new UserDto { userName = user.UserName, token =_tokenService.CreateToken(user) };
        }

        [HttpPost("login")]
        public async Task<ActionResult<UserDto>> Login(LoginDto loginDto)
        {
            //Get the user from database
            var user = await _context.Users.SingleOrDefaultAsync(x =>x.UserName == loginDto.userName.ToLower());
            //If there is no user
            if (user == null) return Unauthorized("Invalid username");

            //validate the entered password
            //Get the password salt saved in the database and add it to the algorithm key
            using var hmac = new HMACSHA512(user.PasswordSalt);
            //verify the hash generated by the user password insertion
            var computedHash = hmac.ComputeHash(Encoding.UTF8.GetBytes(loginDto.password));
            // compare the hash generated with the password hash saved in the database 
            for(int i = 0; i < computedHash.Length; i++)
            {
                if (computedHash[i] != user.PasswordHash[i]) return Unauthorized("Invalid Password");
            }

            return new UserDto { userName = user.UserName, token = _tokenService.CreateToken(user) };

        }

        private async Task<bool> UserExists(string username)
        {
            return await _context.Users.AnyAsync(user => user.UserName.ToLower() == username.ToLower());
        }
    }
}
